machine:
  node:
    version: stable
  environment:
    JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/
    JUNIT_REPORT_NAME: test-results.xml

general:
  artifacts:
    - "coverage" # relative to the user's home directory
    - $CIRCLE_TEST_REPORTS

dependencies:
  pre:
    # update locally with:
    # openssl aes-256-cbc -e -in secret-env-plain -out secret-env-cipher -k $KEY
    - openssl aes-256-cbc -d -in secret-env-cipher -k $key >> ~/.circlerc
  override:
    - npm install

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - run: npm install
      - run: ./node_modules/.bin/gulp build-ci

test:
  override:
      ./node_modules/.bin/gulp build-ci;