machine:
  node:
    version: stable
  environment:
    JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/
    JUNIT_REPORT_NAME: test-results.xml

general:
  branches:
    only:
      - SB1
  artifacts:
    - "coverage" # relative to the user's home directory
    - $CIRCLE_TEST_REPORTS

dependencies:
  override:
    - npm install

test:
  override:
      ./node_modules/.bin/gulp build-ci;