version: 2

jobs:
  build:
    machine:
      node:
        version: current
      environment:
        JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/
        JUNIT_REPORT_NAME: test-results.xml
    steps:
      - checkout
      - run: npm install
      - run: npm link gulp
      - run: npm link karma
      - run: mkdir ~/junit
      - run:
          command: gulp build-ci
      - run:
          command: karma start ./karma.conf.js
          environment:
            JUNIT_REPORT_PATH: ./junit/
            JUNIT_REPORT_NAME: test-results.xml
          when: always  
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit