version: 2

jobs:
  build:
    machine:
      node:
        version: stable
      environment:
        JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/
        JUNIT_REPORT_NAME: test-results.xml
    steps:
      - run: npm install
      - save_cache:
        name: cache
        key: cache
        paths:
          - ~/
      - run: ls
      - run: ./node_modules/.bin/gulp build-ci