version: 2

jobs:
  build:
    machine:
      node:
        version: stable
      environment:
        JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/
        JUNIT_REPORT_NAME: test-results.xml
    steps:
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node_modules
      - run: npm install
      - run: ls
      - run: cd ../
      - run: ls
      - run: cd ../
      - run: ls
      - run: cd ../
      - run: ls
      - run: cd ../
      - run: ls
      - run: cd ../
      - run: ls
      - run: cd ../
      - run: ls
      - run: cd ../