jobs:
  buildTheStuff:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: mkdir ~/junit
      - run:
          command: gulp build-ci
      - run:
          command: karma start ./karma.conf.js
          environment:
            JUNIT_REPORT_PATH: ./junit/
            JUNIT_REPORT_NAME: test-results.xml
          when: always  
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

orbs:
  node: circleci/node@4.1.0
  
version: 2.1
workflows:
  test_my_app:
    jobs:
      - buildTheStuff