machine:
  node:
    version: stable
  environment:
    JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/
    JUNIT_REPORT_NAME: test-results.xml

general:
  artifacts:
    - "coverage" # relative to the user's home directory
    - $CIRCLE_TEST_REPORTS

jobs:
    - run: npm install
    - run: ./node_modules/.bin/gulp build-ci