version: 2

jobs:
  build:
    machine:
      node:
        version: stable
      environment:
        JUNIT_REPORT_PATH: $CIRCLE_TEST_REPORTS/
        JUNIT_REPORT_NAME: test-results.xml
    steps:
      - run: npm install
      - run: npm install -g gulp
      - run: gulp build-ci